##
# C++ for Lam's Algorithms
# Author: Lam Duong
#
# @file
# @version 0.1

GHC = ghc

TARGET = Algorithms
all: $(TARGET)
$(TARGET): $(TARGET).hs
	$(GHC) -o $(TARGET) $(TARGET).hs
clean:
	$(RM) $(TARGET) $(TARGET).hi $(TARGET).o

# end
